--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RxDuZ/SimpleCrates
build-by-default: true
branches:
  - main
projects:
  SimpleCrates:
    path: ""
    icon: "img/SimpleCrates.png"
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.7.3
        branch: pm5
      - src: RxDuZ/Commando/Commando
        version: ^3.2.1
      - src: ACM-PocketMine-MP/ConfigUpdater/ConfigUpdater
        version: ^3.0.0
        branch: PM5
