name: SimpleCrates
main: rxduz\crates\Main
api: 5.19.0
version: 3.0.0
author: "iRxDuZ"
description: "Crates plugin for your server!"
softdepend: ["VanillaElytra"]
virions: ["InvMenu", "Commando"]

permissions:
  simplecrates.command.crate:
    default: true
  simplecrates.command.create:
    default: op
  simplecrates.command.delete:
    default: op
  simplecrates.command.list:
    default: op
  simplecrates.command.editor:
    default: op
  simplecrates.command.key:
    default: op
  simplecrates.command.keyall:
    default: op
